version: "3.8"

services:
  database:
    image: postgres:latest
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
